version: '3.4'
services:
  back-end-candidate-test:
    build:
      context: ./
      dockerfile: ./docker/back-end-candidate-test/Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MINIO_STORAGE_PORT: 9000
      MINIO_STORAGE_ACESS_KEY: minio
      MINIO_STORAGE_SECRET_KEY: minio123
      MINIO_STORAGE_HOST: minio
      MINIO_STORAGE_BUCKET: minio-bucket
    links:
      - minio
    depends_on:
      - minio

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
